inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  NewCops: enable

Layout/ExtraSpacing:
  Exclude:
    - '*.gemspec'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundOperators:
  Exclude:
    - '*.gemspec'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '*.gemspec'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*.rb'

Style/DoubleNegation:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'Gemfile'

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RedundantPercentQ:
  Enabled: false
