inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '*.gemspec'

Style/DoubleNegation:
  Enabled: false

Style/ExtraSpacing:
  Exclude:
    - '*.gemspec'

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SpaceAroundOperators:
  Exclude:
    - '*.gemspec'

Style/UnneededPercentQ:
  Enabled: false
