sudo: false
language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.10
  - 2.5.9
  - 2.6.7
  - 2.7.3
  - 3.0.1
  - ruby-head
before_install:
  - |
    if [[ `ruby -v` =~ 2\.[0-2]\.[0-9]+ ]]; then
      gem install rubygems-update -v '<3' && update_rubygems
      gem install bundler -v '<2'
    else
      gem update --system
      gem update bundler
    fi
