version: 1.0.{build}-{branch}

environment:
  matrix:
    - RUBY_VERSION: 200
    - RUBY_VERSION: 200-x64
    - RUBY_VERSION: 21
    - RUBY_VERSION: 21-x64
    - RUBY_VERSION: 22
    - RUBY_VERSION: 22-x64
    - RUBY_VERSION: 23
    - RUBY_VERSION: 23-x64
    - RUBY_VERSION: 24
    - RUBY_VERSION: 24-x64
    - RUBY_VERSION: 25
    - RUBY_VERSION: 25-x64
    - RUBY_VERSION: 26
    - RUBY_VERSION: 26-x64
    - RUBY_VERSION: 27
    - RUBY_VERSION: 27-x64
    - RUBY_VERSION: 30
    - RUBY_VERSION: 30-x64

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake
